export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const CART_EMPTY = "CART_EMPTY";
