export const data = {
  products: [
    {
      name: "Mediterranean Salad",
      category: "Healthy Food",
      image: "/images/products/mediterranean-salad.png",
      rating: 3.5,
      price: 9,
      stock_products: 20,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
    {
      name: "Autumn Soup",
      category: "Healthy Food",
      image: "/images/products/autumn-soup.png",
      rating: 3.5,
      price: 11,
      stock_products: 13,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
    {
      name: "Healthy Trendy Brunch",
      category: "Healthy Food",
      image: "/images/products/healthy-trendy-brunch.png",
      rating: 3.5,
      price: 7,
      stock_products: 7,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
    {
      name: "Healthy Trendy Brunch",
      category: "Healthy Food",
      image: "/images/products/healthy-trendy-brunch.png",
      rating: 3.5,
      price: 7,
      stock_products: 7,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
    {
      name: "Healthy Trendy Brunch",
      category: "Healthy Food",
      image: "/images/products/healthy-trendy-brunch.png",
      rating: 3.5,
      price: 7,
      stock_products: 7,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
    {
      name: "Healthy Trendy Brunch",
      category: "Healthy Food",
      image: "/images/products/healthy-trendy-brunch.png",
      rating: 3.5,
      price: 7,
      stock_products: 7,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacus",
    },
  ],
};
